"""
This type stub file was generated by pyright.
"""

from .object import object

class vtkSimpleMutexLock(object):
    """
    vtkSimpleMutexLock - no description provided.
    
    vtkSimpleMutexLock()
    """
    def Lock(self):
        """
        V.Lock()
        C++: void Lock(void)
        
        Lock the vtkMutexLock
        """
        ...
    
    def Unlock(self):
        """
        V.Unlock()
        C++: void Unlock(void)
        
        Unlock the vtkMutexLock
        """
        ...
    
    def __getattribute__(self, *args, **kwargs):
        """ Return getattr(self, name). """
        ...
    
    def __hash__(self, *args, **kwargs) -> int:
        """ Return hash(self). """
        ...
    
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def __new__(*args, **kwargs):
        """ Create and return a new object.  See help(type) for accurate signature. """
        ...
    
    def __repr__(self, *args, **kwargs):
        """ Return repr(self). """
        ...
    


