"""
This type stub file was generated by pyright.
"""

import vtkmodules.vtkRenderingCore as __vtkmodules_vtkRenderingCore

class vtkCameraPass(__vtkmodules_vtkRenderingCore.vtkRenderPass):
    """
    vtkCameraPass - Implement the camera render pass.
    
    Superclass: vtkRenderPass
    
    Render the camera.
    
    It setups the projection and modelview matrices and can clear the
    background It calls its delegate once. After its delegate returns, it
    restore the modelview matrix stack.
    
    Its delegate is usually set to a vtkSequencePass with a vtkLigthsPass
    and a list of passes for the geometry.
    
    @sa
    vtkRenderPass
    """
    def GetAspectRatioOverride(self):
        """
        V.GetAspectRatioOverride() -> float
        C++: virtual double GetAspectRatioOverride()
        
        Used to override the aspect ratio used when computing the
        projection matrix. This is useful when rendering for
        tile-displays for example.
        """
        ...
    
    def GetDelegatePass(self):
        """
        V.GetDelegatePass() -> vtkRenderPass
        C++: virtual vtkRenderPass *GetDelegatePass()
        
        Delegate for rendering the geometry. If it is NULL, nothing will
        be rendered and a warning will be emitted. It is usually set to a
        vtkSequencePass with a vtkLigthsPass and a list of passes for the
        geometry. Initial value is a NULL pointer.
        """
        ...
    
    def GetNumberOfGenerationsFromBase(self, string):
        """
        V.GetNumberOfGenerationsFromBase(string) -> int
        C++: vtkIdType GetNumberOfGenerationsFromBase(const char *type)
            override;
        
        Given a the name of a base class of this class type, return the
        distance of inheritance between this class type and the named
        class (how many generations of inheritance are there between this
        class and the named class). If the named class is not in this
        class's inheritance tree, return a negative value. Valid
        responses will always be nonnegative. This method works in
        combination with vtkTypeMacro found in vtkSetGet.h.
        """
        ...
    
    def GetNumberOfGenerationsFromBaseType(self, string):
        """
        V.GetNumberOfGenerationsFromBaseType(string) -> int
        C++: static vtkIdType GetNumberOfGenerationsFromBaseType(
            const char *type)
        
        Given a the name of a base class of this class type, return the
        distance of inheritance between this class type and the named
        class (how many generations of inheritance are there between this
        class and the named class). If the named class is not in this
        class's inheritance tree, return a negative value. Valid
        responses will always be nonnegative. This method works in
        combination with vtkTypeMacro found in vtkSetGet.h.
        """
        ...
    
    def IsA(self, string):
        """
        V.IsA(string) -> int
        C++: vtkTypeBool IsA(const char *type) override;
        
        Return 1 if this class is the same type of (or a subclass of) the
        named class. Returns 0 otherwise. This method works in
        combination with vtkTypeMacro found in vtkSetGet.h.
        """
        ...
    
    def IsTypeOf(self, string):
        """
        V.IsTypeOf(string) -> int
        C++: static vtkTypeBool IsTypeOf(const char *type)
        
        Return 1 if this class type is the same type of (or a subclass
        of) the named class. Returns 0 otherwise. This method works in
        combination with vtkTypeMacro found in vtkSetGet.h.
        """
        ...
    
    def NewInstance(self):
        """
        V.NewInstance() -> vtkCameraPass
        C++: vtkCameraPass *NewInstance()
        """
        ...
    
    def ReleaseGraphicsResources(self, vtkWindow):
        """
        V.ReleaseGraphicsResources(vtkWindow)
        C++: void ReleaseGraphicsResources(vtkWindow *w) override;
        
        Release graphics resources and ask components to release their
        own resources.
        \pre w_exists: w!=0
        """
        ...
    
    def SafeDownCast(self, vtkObjectBase):
        """
        V.SafeDownCast(vtkObjectBase) -> vtkCameraPass
        C++: static vtkCameraPass *SafeDownCast(vtkObjectBase *o)
        """
        ...
    
    def SetAspectRatioOverride(self, p_float):
        """
        V.SetAspectRatioOverride(float)
        C++: virtual void SetAspectRatioOverride(double _arg)
        
        Used to override the aspect ratio used when computing the
        projection matrix. This is useful when rendering for
        tile-displays for example.
        """
        ...
    
    def SetDelegatePass(self, vtkRenderPass):
        """
        V.SetDelegatePass(vtkRenderPass)
        C++: virtual void SetDelegatePass(vtkRenderPass *delegatePass)
        
        Delegate for rendering the geometry. If it is NULL, nothing will
        be rendered and a warning will be emitted. It is usually set to a
        vtkSequencePass with a vtkLigthsPass and a list of passes for the
        geometry. Initial value is a NULL pointer.
        """
        ...
    
    def __delattr__(self, *args, **kwargs):
        """ Implement delattr(self, name). """
        ...
    
    def __getattribute__(self, *args, **kwargs):
        """ Return getattr(self, name). """
        ...
    
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @staticmethod
    def __new__(*args, **kwargs):
        """ Create and return a new object.  See help(type) for accurate signature. """
        ...
    
    def __repr__(self, *args, **kwargs):
        """ Return repr(self). """
        ...
    
    def __setattr__(self, *args, **kwargs):
        """ Implement setattr(self, name, value). """
        ...
    
    def __str__(self, *args, **kwargs) -> str:
        """ Return str(self). """
        ...
    
    __this__ = ...
    __dict__ = ...
    __vtkname__ = ...


