"""
This type stub file was generated by pyright.
"""

from .vtkRect_IiE import vtkRect_IiE

class vtkRecti(vtkRect_IiE):
    """
    vtkRecti - no description provided.
    
    Superclass: vtkRect[int32]
    
    vtkRecti()
    vtkRecti(int x, int y, int width, int height)
    explicit vtkRecti(const int *init)
    vtkRecti(const &vtkRecti)
    """
    def __getattribute__(self, *args, **kwargs):
        """ Return getattr(self, name). """
        ...
    
    def __hash__(self, *args, **kwargs) -> int:
        """ Return hash(self). """
        ...
    
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def __new__(*args, **kwargs):
        """ Create and return a new object.  See help(type) for accurate signature. """
        ...
    
    def __repr__(self, *args, **kwargs):
        """ Return repr(self). """
        ...
    


