"""
This type stub file was generated by pyright.
"""

from .vtkVector3_IiE import vtkVector3_IiE

class vtkVector3i(vtkVector3_IiE):
    """
    vtkVector3i - no description provided.
    
    Superclass: vtkVector3[int32]
    
    vtkVector3i()
    vtkVector3i(int x, int y, int z)
    explicit vtkVector3i(int s)
    explicit vtkVector3i(const int *i)
    explicit vtkVector3i(const vtkTuple<int, 3> &o)
    vtkVector3i(const vtkVector<int, 3> &o)
    vtkVector3i(const &vtkVector3i)
    """
    def Cross(self, vtkVector3i):
        """
        V.Cross(vtkVector3i) -> vtkVector3i
        C++: vtkVector3i Cross(const vtkVector3i &other)
        """
        ...
    
    def Normalized(self):
        """
        V.Normalized() -> vtkVector3i
        C++: vtkVector3i Normalized()
        
        Return the normalized form of this vector.
        \return The normalized form of this vector.
        """
        ...
    
    def __getattribute__(self, *args, **kwargs):
        """ Return getattr(self, name). """
        ...
    
    def __hash__(self, *args, **kwargs) -> int:
        """ Return hash(self). """
        ...
    
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def __new__(*args, **kwargs):
        """ Create and return a new object.  See help(type) for accurate signature. """
        ...
    
    def __repr__(self, *args, **kwargs):
        """ Return repr(self). """
        ...
    


